platform :ios, '12.0'

# Uncomment the next line if you're using Swift
# use_frameworks!

target 'Runner' do
  # Flutter's generated Podfile contents
  use_frameworks!
  # Add this line to include Flutter's iOS dependencies
  install! 'cocoapods', :disable_input_output_paths => true
  flutter_application_path = File.join(File.dirname(File.realpath(__FILE__)), '..')
  load File.join(flutter_application_path, '.flutter-plugins')
  load File.join(flutter_application_path, '.flutter-plugins-dependencies')
end
